# Generated by Django 4.1.7 on 2023-02-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_title_name_alter_title_v_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='base.channel'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(default='others', to='base.tag'),
        ),
    ]
