# Generated by Django 4.1.7 on 2023-02-26 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_channel_name_alter_title_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='tit',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
